os = $(shell uname -s)

INCFLAGS      =  -I$(shell root-config --incdir) -I$(FASTJETDIR)/include -I$(PYTHIA8DIR)/include -I$(BOOSTDIR)/include -I$(STARPICODIR) # -I$(BOOSTDIR)/include
#-I$(shell fastjet-config --cxxflags) #-I$(shell pythia8-config --includedir)

ifeq ($(os),Linux)
CXXFLAGS      = -std=c++11
else
CXXFLAGS      = -O -std=c++11 -fPIC -pipe -Wall -Wno-deprecated-writable-strings -Wno-unused-variable -Wno-unused-private-field -Wno-gnu-static-float-init
## for debugging:
# CXXFLAGS      = -g -O0 -fPIC -pipe -Wall -Wno-deprecated-writable-strings -Wno-unused-variable -Wno-unused-private-field -Wno-gnu-static-float-init
endif

ifeq ($(os),Linux)
LDFLAGS       = -g
LDFLAGSS      = -g --shared
else
LDFLAGS       = -O -Xlinker -bind_at_load -flat_namespace
LDFLAGSS      = -flat_namespace -undefined suppress
LDFLAGSSS     = -bundle
endif

ifeq ($(os),Linux)
CXX          = g++
else
CXX          = clang
endif


ROOTLIBS      = $(shell root-config --libs)
#FJLIBS        = $(shell fastjet-config --plugins=yes --libs)
#PYTHIALIBS    = $(shell pythia8-config --ldflags)
LIBPATH       = -L$(FASTJETDIR)/lib -L$(STARPICODIR) $(shell root-config --libs)
#LIBS          =  $(ROOTLIBS) $(FJLIBS) $(PYTHIALIBS)
LIBS		= -lfastjet -lfastjettools -lTStarJetPico

# for cleanup
SDIR          = src
ODIR          = src/obj
BDIR          = bin


###############################################################################
################### Remake when these headers are touched #####################
###############################################################################


###############################################################################
# standard rules
$(ODIR)/%.o : $(SDIR)/%.cxx $(INCS)
	@echo
	@echo COMPILING
	$(CXX) $(CXXFLAGS) $(INCFLAGS) -c $< -o $@

$(BDIR)/%  : $(ODIR)/%.o
	@echo
	@echo LINKING
	$(CXX) $(LDFLAGS) $^ -o $@ $(LIBPATH) $(LIBS)

###############################################################################

###############################################################################
############################# Main Targets ####################################
###############################################################################
all : $(BDIR)/analysis

#create dictionary
#$(SDIR)/dict.cxx :	$(SDIR)/ktTrackEff.hh
#	cd ${SDIR}; rootcint -f dict.cxx -c -I. ./ktTrackEff.hh

#create objects
#$(ODIR)/dict.o : $(SDIR)/dict.cxx
$(ODIR)/functions.o : $(SDIR)/functions.cxx $(SDIR)/functions.hh
#$(ODIR)/ktTrackEff.o : $(SDIR)/ktTrackEff.cxx $(SDIR)/ktTrackEff.hh
$(ODIR)/analysis.o : $(SDIR)/analysis.cxx

#create binary
$(BDIR)/analysis :	$(ODIR)/analysis.o	$(ODIR)/functions.o	#$(ODIR)/ktTrackEff.o	$(ODIR)/dict.o

###############################################################################
##################################### MISC ####################################
###############################################################################

clean :
	@echo
	@echo CLEANING
	rm -vf $(ODIR)/*.o
	rm -vf $(BDIR)/*
	rm -vf lib/*

